# -*- coding: utf-8 -*-
"""
/***************************************************************************
 JoinLayer
                                 A QGIS plugin
 This code is a QGIS plugin that functions to split polygon layers using a line layer as the cutting centerline. The plugin works by identifying polygon and centerline layers loaded in QGIS, then using GeoPandas and Shapely to process the geometry.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-03-17
        copyright            : (C) 2025 by Muhammad Ihsan
        email                : muhammad.ihsan@upi.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load JoinLayer class from file JoinLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .join_layer import JoinLayer
    return JoinLayer(iface)
